version: "3"
services:
  postgres-db:
    container_name: postgres-db
    env_file:
      - .env-dev
      - .env
    image: postgres:17.2-bookworm
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    # volumes:
    #   - $PWD/initdb:/docker-entrypoint-initdb.d
    networks:
      - backend

networks:
  backend:
    driver: bridge
