version: "3"
services:
  frontend:
    container_name: frontend
    env_file:
      - .env-dev
      - .env
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
